services:
  api:
    build: .
    ports:
      - "8080:8080"  # exponer el mismo puerto que escucha la API
    depends_on:
      - db
    environment:
      MYSQLHOST: db
      MYSQLPORT: 3306
      MYSQLDATABASE: webproductosdb
      MYSQLUSER: root
      MYSQLPASSWORD: Qwe.123*
      Jwt__Key: "TuClaveMuySeguraDeAlMenos32Caracteres"  # seg√∫n tu appsettings.json

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Qwe.123*
      MYSQL_DATABASE: webproductosdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Qwe.123*
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
