services:
  mysql:
    image: mysql:8.0
    container_name: webproductos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Qwe.123*
      MYSQL_DATABASE: webproductosdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: webproductos-api
    depends_on:
      - mysql
    environment:
      # Forzar entorno de desarrollo para que Swagger se active
      - ASPNETCORE_ENVIRONMENT=Development
      # Cadena de conexi√≥n
      - DefaultConnection=Server=mysql;Database=webproductosdb;User=root;Password=Qwe.123*;
    ports:
      - "5075:8080"

volumes:
  db_data:
