services:
  api:
    build: .
    container_name: webproductos_api 
    ports:
      - "8081:8080"  
    depends_on:
      - db
    environment:
      MYSQLHOST: db
      MYSQLPORT: 3306
      MYSQLDATABASE: webproductosdb
      MYSQLUSER: root
      MYSQLPASSWORD: Qwe.123*
      Jwt__Key: "TuClaveMuySeguraDeAlMenos32Caracteres"

  db:
    image: mysql:8.0
    container_name: webproductos_db
    environment:
      MYSQL_ROOT_PASSWORD: Qwe.123*
      MYSQL_DATABASE: webproductosdb
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
