services:
  api:
    build: .
    ports:
      - "8081:8080"  # exponer el mismo puerto que escucha la API
    depends_on:
      - db
    environment:
      MYSQLHOST: db   # antes estaba localhost, cambié a 'db' para que se conecte al contenedor
      MYSQLPORT: 3306
      MYSQLDATABASE: webproductosdb
      MYSQLUSER: root
      MYSQLPASSWORD: Qwe.123*
      Jwt__Key: "TuClaveMuySeguraDeAlMenos32Caracteres"  # según tu appsettings.json

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Qwe.123*
      MYSQL_DATABASE: webproductosdb
      # MYSQL_USER: root    #  eliminado porque no se puede usar 'root' como usuario regular
      # MYSQL_PASSWORD: Qwe.123*  #  eliminado por la misma razón
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
